branches:
  only:
    - master
language: node_js
node_js:
  - "10"
  - "12"
script:
  - bin/lint
  - bin/build
  - bin/jest --collectCoverageFrom='src/**'
  - bin/codecov --disable=gcov --file=coverage/coverage-final.json
